/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import controlador.Empresa;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import modelo.Curso;

/**
 *
 * @author dam
 */
public class AltaAlu extends javax.swing.JPanel {

    DefaultComboBoxModel modelo;
    Empresa empresa;

    /**
     * Creates new form AltaAlu
     */
    public AltaAlu(Empresa empresa) {
        this.empresa = empresa;
        initComponents();
        modelo = new DefaultComboBoxModel();
        jcCursos.setModel(modelo);
        cargarCursos();
    }

    private void cargarCursos() {
        modelo.addElement("Seleccione un curso");
        modelo.addAll(empresa.getCursos());
        /*ArrayList<Curso> cursos = empresa.getCursos();
        for (int i = 0; i < cursos.size(); i++) {
            modelo.addElement(cursos.get(i));
        }*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btGuardar = new javax.swing.JButton();
        btCancelar = new javax.swing.JButton();
        txtDNI = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        jcCursos = new javax.swing.JComboBox<>();

        jLabel1.setText("DNI");

        jLabel2.setText("Nombre");

        jLabel3.setText("Curso");

        btGuardar.setText("Guardar");
        btGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGuardarActionPerformed(evt);
            }
        });

        btCancelar.setText("Cancelar");

        jcCursos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcCursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcCursosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(btGuardar)
                        .addGap(83, 83, 83)
                        .addComponent(btCancelar)
                        .addContainerGap(108, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtDNI, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jcCursos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(txtDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jcCursos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCancelar)
                    .addComponent(btGuardar))
                .addGap(28, 28, 28))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jcCursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcCursosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcCursosActionPerformed

    private void btGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGuardarActionPerformed
        int pos = jcCursos.getSelectedIndex();
        String dni = txtDNI.getText();
        String nombre = txtNombre.getText();
        if (!(modelo.getElementAt(pos).getClass().equals("java.lang.String"))) {
            if (pos != 0) {
                Curso c = (Curso) modelo.getElementAt(pos);
                if (empresa.existeAlumno2(dni)) {
                    JOptionPane.showMessageDialog(this, "Dni Existente", "Error", JOptionPane.ERROR_MESSAGE);
                    txtDNI.setText("");
                    txtDNI.requestFocus();
                } else {
                    if (nombre.trim().equals("")) {
                        JOptionPane.showMessageDialog(this, "Campo requerido", "Error", JOptionPane.ERROR_MESSAGE);
                        txtNombre.requestFocus();
                    } else {
                        empresa.anadirAlumno(dni, nombre, c);
                        JOptionPane.showMessageDialog(this, "Alumno Grabado", "Informacion", JOptionPane.INFORMATION_MESSAGE);
                        borrar();
                    }
                }
            }else{
                JOptionPane.showMessageDialog(this, "Selecciona un curso","Error",JOptionPane.ERROR_MESSAGE);
                jcCursos.requestFocus();
            }
        }
    }//GEN-LAST:event_btGuardarActionPerformed

    private void borrar() {
        txtDNI.setText("");
        txtNombre.setText("");
        jcCursos.setSelectedIndex(0);
        txtDNI.requestFocus();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btGuardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JComboBox<String> jcCursos;
    private javax.swing.JTextField txtDNI;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
