/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import controlador.Empresa;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import modelo.Asignatura;

/**
 *
 * @author dam
 */
public class AltaCurso extends javax.swing.JPanel {

    Empresa empresa;
    DefaultListModel modeloAsig;
    DefaultListModel modeloSelec;

    /**
     * Creates new form AltaCurso
     */
    public AltaCurso(Empresa empresa) {
        this.empresa = empresa;
        initComponents();
        modeloAsig = new DefaultListModel();
        listaOferta.setModel(modeloAsig);
        cargarAsginaturas();
        modeloSelec = new DefaultListModel();
        listaEscoger.setModel(modeloSelec);
        habilitar();
    }

    private void cargarAsginaturas() {
        ArrayList<Asignatura> asigna = empresa.getAsignaturas();
        modeloAsig.addAll(asigna); //En esto cada elemento es de tipo Asignatura, mientras que en el for solo es Strings
        /*     for (int i = 0; i < asigna.size(); i++) {
           // modeloAsig.addElement(asigna.get(i).getNombre());
        }*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbCodigo = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        lbDenominacion = new javax.swing.JLabel();
        txtDenominacion = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaOferta = new javax.swing.JList<>();
        botonNoEscoger = new javax.swing.JButton();
        botonEscoger = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaEscoger = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();
        Guardar = new javax.swing.JButton();
        btCancelar = new javax.swing.JButton();

        lbCodigo.setText("CODIGO");

        lbDenominacion.setText("DENOMINACION");

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        jLabel1.setText("ALTA CURSOS");

        jLabel2.setText("Asignaturas ofertadas");

        listaOferta.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Programacion", "Entornos", "Fol", "Lenguaje de Marcas", "Sistemas Informaticos" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listaOferta.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(listaOferta);

        botonNoEscoger.setText("<<");
        botonNoEscoger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNoEscogerActionPerformed(evt);
            }
        });

        botonEscoger.setText(">>");
        botonEscoger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEscogerActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(listaEscoger);

        jLabel3.setText("Asignaturas Escogidas");

        Guardar.setText("Guardar");
        Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarActionPerformed(evt);
            }
        });

        btCancelar.setText("Cancelar");
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lbCodigo)
                        .addComponent(lbDenominacion))
                    .addComponent(Guardar))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(64, 64, 64))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtDenominacion, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(77, 77, 77)
                                .addComponent(btCancelar)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botonEscoger)
                            .addComponent(botonNoEscoger))
                        .addGap(25, 25, 25)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCodigo)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDenominacion, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDenominacion, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(botonEscoger)
                        .addGap(18, 18, 18)
                        .addComponent(botonNoEscoger)
                        .addGap(37, 37, 37)))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Guardar)
                    .addComponent(btCancelar))
                .addContainerGap(32, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        txtCodigo.setText("");
        txtDenominacion.setText("");
    }//GEN-LAST:event_btCancelarActionPerformed

    private void GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarActionPerformed
        int codigo = 0;
        ArrayList<Asignatura> a = new ArrayList<>();
        try {
            codigo = Integer.parseInt(txtCodigo.getText());
            String deno = txtDenominacion.getText().trim();
            if (deno.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Denominacion es un campo requerido", "Error", JOptionPane.ERROR_MESSAGE);
                txtDenominacion.requestFocus();
            } else {
                if (modeloSelec.size() == 0) {
                    JOptionPane.showMessageDialog(this, "Al menos debe seleccionar una asignatura", "Error", JOptionPane.ERROR_MESSAGE);
                } else {
                    for (int i = 0; i < modeloSelec.size(); i++) {
                        a.add((Asignatura) modeloSelec.getElementAt(i));
                    }
                    if (empresa.exixsteCurso(codigo)) {
                        JOptionPane.showMessageDialog(this, "Curso Existente", "Error", JOptionPane.ERROR_MESSAGE);
                        txtCodigo.setText("");
                        txtCodigo.requestFocus();
                    } else {
                        empresa.anadirCurso(a, codigo, deno);
                        JOptionPane.showMessageDialog(this, "Curso añadido", "Informacion", JOptionPane.INFORMATION_MESSAGE);
                        limpiar();
                    }
                }
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "El codigo debe de ser un numero", "Error", JOptionPane.ERROR_MESSAGE);
            txtCodigo.setText("");
            txtCodigo.requestFocus();
        }
        /*       int codigo;
        ArrayList<Asignatura> asigna = empresa.getAsignaturas();
        try {
            codigo = Integer.parseInt(txtCodigo.getText());
            if (!empresa.buscarCurso(codigo)) {
                txtDenominacion.setText("Existe?");
            } else {
                txtDenominacion.setText("No existe");
            }
        } catch (NumberFormatException ex) {
        }
         */
    }//GEN-LAST:event_GuardarActionPerformed

    private void limpiar() {
        txtDenominacion.setText("");
        txtCodigo.setText("");
        modeloSelec.clear();
        modeloAsig.clear();
        cargarAsginaturas();
    }

    private void botonEscogerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEscogerActionPerformed
        int posicion = listaOferta.getSelectedIndex();
        if (posicion != -1) {
            Asignatura a = (Asignatura) modeloAsig.getElementAt(posicion);
            modeloSelec.addElement(a);
            modeloAsig.remove(posicion);
            habilitar();
        } else {
            JOptionPane.showMessageDialog(this, "Primero seleccione una asignatura", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_botonEscogerActionPerformed

    private void botonNoEscogerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNoEscogerActionPerformed
        int posicion = listaEscoger.getSelectedIndex();
        if (posicion != -1) {
            Asignatura a = (Asignatura) modeloSelec.getElementAt(posicion);
            modeloAsig.addElement(a);
            modeloSelec.remove(posicion);
            habilitar();
        } else {
            JOptionPane.showMessageDialog(this, "Primero seleccione una asignatura", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_botonNoEscogerActionPerformed
    private void habilitar() {
        if (modeloSelec.isEmpty()) {
            botonNoEscoger.setEnabled(false);
        } else {
            botonNoEscoger.setEnabled(true);
            if (modeloAsig.isEmpty()) {
                botonEscoger.setEnabled(false);
            } else {
                botonEscoger.setEnabled(true);
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Guardar;
    private javax.swing.JButton botonEscoger;
    private javax.swing.JButton botonNoEscoger;
    private javax.swing.JButton btCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbCodigo;
    private javax.swing.JLabel lbDenominacion;
    private javax.swing.JList<String> listaEscoger;
    private javax.swing.JList<String> listaOferta;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtDenominacion;
    // End of variables declaration//GEN-END:variables
}
