/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.Empresa;

/**
 *
 * @author dam
 */
public class VntGestor extends javax.swing.JFrame {
    
    Empresa empresa;
    AltaCurso altacurso;
    AltaAlu altaalumnos;
    ConsultaAlu consultaalu;

    /**
     * Creates new form VntGestor
     */
    public VntGestor() {
        initComponents();
    }
    
    public VntGestor(Empresa e) {
        initComponents();
        empresa = e;        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        menuAlumnos = new javax.swing.JMenu();
        AltaAlu = new javax.swing.JMenuItem();
        ConsultaAlu = new javax.swing.JMenuItem();
        menuCurso = new javax.swing.JMenu();
        AltaCurso = new javax.swing.JMenuItem();
        menuSalir = new javax.swing.JMenu();
        Desconectar = new javax.swing.JMenuItem();
        Salir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.FlowLayout());

        menuAlumnos.setText("Alumnos");

        AltaAlu.setText("Alta");
        AltaAlu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AltaAluActionPerformed(evt);
            }
        });
        menuAlumnos.add(AltaAlu);

        ConsultaAlu.setText("Consulta");
        ConsultaAlu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultaAluActionPerformed(evt);
            }
        });
        menuAlumnos.add(ConsultaAlu);

        jMenuBar1.add(menuAlumnos);

        menuCurso.setText("Curso");

        AltaCurso.setText("Alta");
        AltaCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AltaCursoActionPerformed(evt);
            }
        });
        menuCurso.add(AltaCurso);

        jMenuBar1.add(menuCurso);

        menuSalir.setText("Salir");

        Desconectar.setText("Desconectar sesion");
        Desconectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DesconectarActionPerformed(evt);
            }
        });
        menuSalir.add(Desconectar);

        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });
        menuSalir.add(Salir);

        jMenuBar1.add(menuSalir);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AltaCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AltaCursoActionPerformed
        quitarPaneles();
        altacurso = new AltaCurso(empresa);
        this.getContentPane().add(altacurso);
        pack();
    }//GEN-LAST:event_AltaCursoActionPerformed

    private void ConsultaAluActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultaAluActionPerformed
        quitarPaneles();
        consultaalu = new ConsultaAlu();
        this.getContentPane().add(consultaalu);
        pack();
    }//GEN-LAST:event_ConsultaAluActionPerformed

    private void AltaAluActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AltaAluActionPerformed
        quitarPaneles();
        altaalumnos = new AltaAlu();
        this.getContentPane().add(altaalumnos);
        pack();
    }//GEN-LAST:event_AltaAluActionPerformed

    private void DesconectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DesconectarActionPerformed
        new VntLogin(empresa).setVisible(true);
        dispose();
        pack();
    }//GEN-LAST:event_DesconectarActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        dispose();
        System.exit(0);
    }//GEN-LAST:event_SalirActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AltaAlu;
    private javax.swing.JMenuItem AltaCurso;
    private javax.swing.JMenuItem ConsultaAlu;
    private javax.swing.JMenuItem Desconectar;
    private javax.swing.JMenuItem Salir;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuAlumnos;
    private javax.swing.JMenu menuCurso;
    private javax.swing.JMenu menuSalir;
    // End of variables declaration//GEN-END:variables

    private void quitarPaneles() {
        try {
            this.getContentPane().remove(altacurso);
        } catch (Exception ex) {
        }
        try {
            this.getContentPane().remove(altaalumnos);
        } catch (Exception ex) {
        }
        try {
            this.getContentPane().remove(consultaalu);
        } catch (Exception ex) {
        }
    }
}
